apiVersion: apps/v1
kind: Deployment
metadata:
  name: mtbiapp
  labels:
    app: mtbi
spec:
  selector:
    matchLabels:
      app: mtbi
  template:
    metadata:
      labels:
        app: mtbi
    spec:
      containers:
      - name: "nodejs-backend"
        image: mrppdex/mbti_backend
        ports:
        - containerPort: 33333
      - name: "mbti-i"
        image: mrppdex/mbti_i
        env:
        - name: "PORT"
          value: "30001"     
      - name: "mbti-n"
        image: mrppdex/mbti_n
        env:
        - name: "PORT"
          value: "30002"
      - name: "mbti-t"
        image: mrppdex/mbti_t
        env:
        - name: "PORT"
          value: "30003"
      - name: "mbti-j"
        image: mrppdex/mbti_j
        env:
        - name: "PORT"
          value: "30004"
          

      