apiVersion: apps/v1
kind: Deployment
metadata:
  name: mtbiapp
  labels:
    app: mtbi
spec:
  selector:
    matchLabels:
      app: mtbi
  template:
    metadata:
      labels:
        app: mtbi
    spec:
      containers:
      - name: "backend"
        image: mrppdex/mbti_backend
        ports:
        - containerPort: 8080
      - name: "mbti-i"
        image: mrppdex/mbti_i
        ports:
        - containerPort: 30001      
      - name: "mbti-n"
        image: mrppdex/mbti_n
        ports:
        - containerPort: 30002

      