apiVersion: apps/v1
kind: Deployment
metadata:
  name: mbtiapp
  labels:
    app: mbti
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mbti
  template:
    metadata:
      labels:
        app: mbti
    spec:
      containers:
      - name: "nodejs-backend"
        image: mrppdex/mbti_backend
        ports:
        - containerPort: 33333
        env:
        - name: "NODE_ENV"
          value: "production"  
      - name: "mbti-i"
        image: mrppdex/mbti_i
        env:
        - name: "PORT"
          value: "30001"   
      - name: "mbti-n"
        image: mrppdex/mbti_n
        env:
        - name: "PORT"
          value: "30002"
      - name: "mbti-t"
        image: mrppdex/mbti_t
        env:
        - name: "PORT"
          value: "30003"
      - name: "mbti-j"
        image: mrppdex/mbti_j
        env:
        - name: "PORT"
          value: "30004"


      