apiVersion: apps/v1
kind: Deployment
metadata:
  name: mtbiapp
  labels:
    app: mtbi
spec:
  selector:
    matchLabels:
      app: hello
      what: backend
  template:
    metadata:
      labels:
        app: mtbi
    spec:
      containers:
      - name: backend
        image: mrppdex/mbti_backend
        labels:
          what: backend
        ports:
        - containerPort: 8080
        - port: 80
      - name: mbti_i
        image: mrppdex/mbti_i
        ports:
        - containerPort: 5000
        - port: 30001
      - name: mbti_i
        image: mrppdex/mbti_n
        ports:
        - containerPort: 5000
        - port: 30002

      